apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coredns-crd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "coredns-crd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels: {{- include "coredns-crd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "coredns-crd.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "coredns-crd.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: {{ .Values.topologySpreadConstraints.maxSkew }}
          topologyKey: {{ .Values.topologySpreadConstraints.topologyKey }}
          whenUnsatisfiable: {{ .Values.topologySpreadConstraints.whenUnsatisfiable }}
          labelSelector:
            matchLabels: {{- include "coredns-crd.selectorLabels" . | nindent 14 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: coredns
          image: {{ include "coredns-crd.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-conf", "/etc/coredns/Corefile"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
              readOnly: true
          ports:
            - containerPort: {{ .Values.service.ports.dns }}
              name: dns
              protocol: UDP
            - containerPort: {{ .Values.service.ports.dnsTcp }}
              name: dns-tcp
              protocol: TCP
            - containerPort: {{ .Values.service.ports.metrics }}
              name: metrics
              protocol: TCP
          resources: {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add: [NET_BIND_SERVICE]
              drop: [all]
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8181
              scheme: HTTP
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "coredns-crd.fullname" . }}
            items:
              - key: Corefile
                path: Corefile
