{{- if .Values.leaderElection.enabled }}
{{- $leaderName := printf "%s-leader" (include "coredns-crd.fullname" .) | trunc 63 | trimSuffix "-" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $leaderName }}
  namespace: {{ include "coredns-crd.leaseNamespace" . }}
  labels: {{- include "coredns-crd.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $leaderName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "coredns-crd.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
