{{- if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "coredns-crd.fullname" . }}-leader
  namespace: {{ include "coredns-crd.leaseNamespace" . }}
  labels: {{- include "coredns-crd.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "coredns-crd.fullname" . }}-leader
subjects:
  - kind: ServiceAccount
    name: {{ include "coredns-crd.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
