apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coredns-crd.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "coredns-crd.labels" . | nindent 4 }}
